workflows:
  build-ios:
    name: Build iOS App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.eimec.app
        APP_NAME: EIMEC
      node: 18.18.2
    cache:
      cache_paths:
        - ~/.npm
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Compilar Vue (build de producción)
        script: |
          npm run build
      - name: Sincronizar Capacitor
        script: |
          npx cap sync ios
      - name: Construir proyecto iOS con Xcode
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/build/App.xcarchive
    artifacts:
      - build/**/App.xcarchive
      - ios/build/Build/Products/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - tu-email@dominio.com
        notify:
          success: true
          failure: true
